#!/bin/sh
chosen="$(grep -v '#' ~/.config/sway/emoji-list | rofi -dmenu -i -p emoji)"
[ -z "$chosen" ] && exit
c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | wl-copy
notify-send "'$c' copied to clipboard."
