#!/bin/sh
if [ "$1" = '-n' ]; then
    grace=0
else
    grace=10
fi

exec swaylock \
    --screenshots \
    --effect-blur 10x5 \
    --effect-compose "0,-1;-1x50%;southwest;$HOME/Pictures/lockscreen.png" \
    --clock \
    --indicator \
    --text-color FFFFFFFF \
    --grace "$grace" \
    --fade-in 1 \
    --font 'DejaVu Sans Mono'
