#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

git ls-tree -r --name-only HEAD | grep '^\.' | while read -r file; do
    cp "$HOME/$file" "$DIR/$file"
done

git -C "$DIR" diff
